Update server-manager due to GRPC interface changes
cartesi/server-manager pull request #3
Opened 2023-06-06 18:14 UTC by vfusco

For more information see https://github.com/cartesi/rollups/issues/10

2023-06-06 20:56 UTC, gligneul approved these changes

2023-06-07 13:21 UTC, diegonehab commented on src/test-server-manager.cpp
> +    ASSERT(validity.output_hash_in_output_hashes_siblings_size() > 0, "Proof should have keccak in hashes siblings");
Fix error message. Are there other instances of the word "keccak" we might have missed?

2023-06-07 13:21 UTC, diegonehab commented on src/test-server-manager.cpp
>          ASSERT(p2.verify(h),
Yes there are.

2023-06-07 13:22 UTC, diegonehab commented on src/test-server-manager.cpp
>              "OutputValidityProof vouchers_epoch_root_hash and output_hashes_in_epoch_siblings verification failed");
Yes there are.

2023-06-07 13:22 UTC, diegonehab commented on src/test-server-manager.cpp
>              "OutputValidityProof output_hashes_root_hash and keccak_in_hashes_siblings verification failed");
Yes there are.

2023-06-07 13:22 UTC, diegonehab commented on src/test-server-manager.cpp
>              "OutputValidityProof output_hashes_root_hash and keccak_in_hashes_siblings verification failed");
Yes there are.

2023-06-07 13:23 UTC, diegonehab requested changes
Some error messages still refer to old fields.

2023-06-07 13:43 UTC, diegonehab approved these changes

2023-06-07 13:57 UTC, merged